"""initial_schema

Revision ID: 34c12187dd95
Revises: 
Create Date: 2026-03-14 23:47:15.672321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34c12187dd95'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plaid_account_id', sa.Text(), nullable=True),
    sa.Column('plaid_item_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('official_name', sa.Text(), nullable=True),
    sa.Column('institution', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('subtype', sa.Text(), nullable=True),
    sa.Column('card_slug', sa.Text(), nullable=True),
    sa.Column('current_balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('available_balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.Text(), server_default='USD', nullable=False),
    sa.Column('mask', sa.Text(), nullable=True),
    sa.Column('last_synced', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_excluded', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plaid_account_id')
    )
    op.create_table('budgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('budget_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'month', name='uq_budget_category_month')
    )
    op.create_table('earn_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_slug', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('subcategory', sa.Text(), nullable=True),
    sa.Column('earn_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('program', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_earn_rules_card', 'earn_rules', ['card_slug'], unique=False, postgresql_where='is_active = TRUE')
    op.create_table('net_worth_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('total_assets', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_liabilities', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_worth', sa.Numeric(precision=14, scale=2), sa.Computed('total_assets - total_liabilities', persisted=True), nullable=False),
    sa.Column('breakdown', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_date')
    )
    op.create_table('plaid_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.Text(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('institution_id', sa.Text(), nullable=True),
    sa.Column('institution_name', sa.Text(), nullable=True),
    sa.Column('sync_cursor', sa.Text(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id')
    )
    op.create_table('points_balances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_slug', sa.Text(), nullable=False),
    sa.Column('program', sa.Text(), nullable=False),
    sa.Column('balance', sa.BigInteger(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('source', sa.Text(), server_default='manual', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_slug', 'as_of', name='uq_points_balance_card_date')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plaid_transaction_id', sa.Text(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('authorized_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.Text(), server_default='USD', nullable=False),
    sa.Column('merchant', sa.Text(), nullable=True),
    sa.Column('raw_description', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('subcategory', sa.Text(), nullable=True),
    sa.Column('category_source', sa.Text(), server_default='pending', nullable=False),
    sa.Column('plaid_category', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('is_transfer', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_excluded', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('reimbursement_note', sa.Text(), nullable=True),
    sa.Column('pending', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('payment_channel', sa.Text(), nullable=True),
    sa.Column('location_address', sa.Text(), nullable=True),
    sa.Column('location_city', sa.Text(), nullable=True),
    sa.Column('location_state', sa.Text(), nullable=True),
    sa.Column('location_zip', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plaid_transaction_id')
    )
    op.create_index('idx_transactions_account_date', 'transactions', ['account_id', 'date'], unique=False)
    op.create_index('idx_transactions_category', 'transactions', ['category'], unique=False, postgresql_where=sa.text('is_excluded = FALSE'))
    op.create_index('idx_transactions_date', 'transactions', ['date'], unique=False)
    op.create_index('idx_transactions_pending', 'transactions', ['pending'], unique=False, postgresql_where=sa.text('pending = TRUE'))
    op.create_table('anomalies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('anomaly_score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), server_default='unreviewed', nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('flagged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id', name='uq_anomaly_transaction')
    )
    op.create_table('points_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('card_slug', sa.Text(), nullable=False),
    sa.Column('program', sa.Text(), nullable=False),
    sa.Column('points_earned', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('earn_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('subcategory', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id', name='uq_points_ledger_transaction')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('points_ledger')
    op.drop_table('anomalies')
    op.drop_index('idx_transactions_pending', table_name='transactions', postgresql_where=sa.text('pending = TRUE'))
    op.drop_index('idx_transactions_date', table_name='transactions')
    op.drop_index('idx_transactions_category', table_name='transactions', postgresql_where=sa.text('is_excluded = FALSE'))
    op.drop_index('idx_transactions_account_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('points_balances')
    op.drop_table('plaid_links')
    op.drop_table('net_worth_snapshots')
    op.drop_index('idx_earn_rules_card', table_name='earn_rules', postgresql_where='is_active = TRUE')
    op.drop_table('earn_rules')
    op.drop_table('budgets')
    op.drop_table('accounts')
    # ### end Alembic commands ###
